(defun pnt(n)
  (when (< n 1) (return-from pnt 0))
  (format t " ")
  (pnt (- n 1)))

(let ((x)
      (xr)
      (y)
      (yr))
  (declare (integer x))
  (declare (integer y))
  (setq xr (random 16))
  (setq x 0)
  (loop
   (loop (when (> x xr) (return))
    (pnt x)
    (format t "*")
    (terpri)
    (setq x (+ x 1))
    (sleep 0.08)
    )
   (setq yr (random x))
   (loop (when (and (< yr x) (not (= yr 0))) (return)) (setq yr (random x)))

   (setq y x)
   (loop (when (< y yr) (return))
    (pnt y)
    (format t "*")
    (terpri)
    (setq y (- y 1))
    (sleep 0.08)
    )

   (setq xr (random 16))
   (loop (when (and (> xr y) (not (= xr 0))) (return)) (setq xr (random 16)))
   (setq x y)
   )
  )
