(let ((i)
      (x))
  (declare (real i))
  (setq i 0)
  (loop
   (setq x 0)
   (loop (when (> x (abs (* (sin i) 100))) (return))
    (format t " ")
    (setq x (+ x 1))
    )
   (format t "*")
   (terpri)
   (setq i (+ i 0.08))
   (sleep 0.05)
   )
  )
